<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-01-23 at 16:15:38.
 */

include  'lib/ValidationStrategyLength.php';

class ValidationStrategyLengthTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ValidationStrategyLength
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ValidationStrategyLength(4);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ValidationStrategyLength::test
     */
    public function testTest()
    {
        $rs = $this->object->test('abc12345');
        $this->assertTrue($rs);
    }

    public function testTestFailTooFew()
    {
        $rs = $this->object->test('12ab');
        $this->assertFalse($rs);
    }

    /**
     * @covers ValidationStrategyLength::getMessage
     */
    public function testGetMessage()
    {
        $expect = 'Needs to be more than 4 characters long';
        $actual = $this->object->getMessage();
        $this->assertEquals($expect, $actual);
    }
}
